/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package example.introduction

import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

class HelloWorldTest {
    @Test
    fun testAppHasAGreeting() {
        assertNotNull(App().greeting, "app should have a greeting")
    }
}
