/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample.app;

import sample.list.LinkedList;

import static sample.utilities.StringUtils.join;
import static sample.utilities.StringUtils.split;
import static sample.app.MessageUtils.getMessage;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        System.out.println(join(tokens));
    }
}
